name: package-build

on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      APK_MAINTAINER: ${{ secrets.APK_MAINTAINER }}
      APK_PACKAGER: ${{ secrets.APK_PACKAGER }}
      BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
      BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}

    strategy:
      matrix:
        alpine: [ "3.12", "3.11" ]
        php: [ "8.0", "7.4" ]

    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: build-wip
        env:
          APK_MAINTAINER: ${{ secrets.APK_MAINTAINER }}
          APK_PACKAGER: ${{ secrets.APK_PACKAGER }}
          BINTRAY_USERNAME: ${{ secrets.BINTRAY_USERNAME }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
          ALPINE_VERSION: ${{ matrix.alpine }}
          PHP_VERSION: ${{ matrix.php }}
        run: |
          echo ${{ secrets.PHP_ALPINE_RSA }} > .abuild/php-alpine.rsa
          echo ${{ secrets.PHP_ALPINE_RSA_PUB }} > .abuild/php-alpine.rsa.pub
          curl -L https://github.com/docker/compose/releases/download/1.21.2/docker-compose-`uname -s`-`uname -m` -o ./docker-compose
          chmod +x ./docker-compose
          ./docker-compose run shell ./build --full
